---
- hosts: control_plane
  become: yes
  tasks:

    - name: install kubectl
      apt:
       name: kubectl
       state: present
       force: yes

    - name: hold kubectl package to prevent updates
      command: apt-mark hold kubectl


    - name: Initialize the Kubernetes cluster using kubeadm
      shell: kubeadm init  --cri-socket=unix:///var/run/crio/crio.sock --ignore-preflight-errors=all  --pod-network-cidr=192.168.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create the .kube directory
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
